include $(srctree)/google-modules/google-modules.conf

LINUXINCLUDE += -include $(srctree)/google-modules/google-modules-conf.h

obj-y += amplifiers/audiometrics/
obj-y += amplifiers/cs35l41/
obj-y += amplifiers/cs35l45/
obj-y += amplifiers/cs40l26/
obj-y += amplifiers/drv2624/
obj-y += aoc/
obj-y += aoc/alsa/
obj-y += aoc/usb/
obj-y += bluetooth/qcom/
obj-y += bms/
obj-y += display/samsung/
obj-y += edgetpu/janeiro/drivers/edgetpu/
obj-y += gpu/mali_kbase/
obj-y += gpu/mali_pixel/
obj-y += gxp/gs201/
obj-y += lwis/
obj-y += nfc/
obj-y += power/reset/
obj-y += touch/common/
obj-y += touch/focaltech/ft3658/
obj-y += touch/goodix/
obj-y += uwb/qorvo/dw3000/kernel/
obj-y += video/gchips/
obj-y += wlan/wcn6740/cnss2/
obj-y += wlan/wcn6740/wlan/qcacld-3.0/
obj-y += devices/google/lynx/display/
